# Generated by Django 4.1.5 on 2023-02-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_user"),
        ("seller_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerproduct",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sellerproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seller_products",
                to="products.product",
            ),
        ),
    ]
