# Generated by Django 4.1.5 on 2023-01-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cat_name",
                    models.CharField(max_length=200, verbose_name="name of category"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Merch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="merch name")),
                ("price", models.FloatField(verbose_name="price")),
                ("description", models.TextField(verbose_name="description")),
                ("quantity", models.IntegerField(verbose_name="quantity")),
                ("is_active", models.BooleanField(verbose_name="active")),
            ],
        ),
    ]
