# Generated by Django 4.1.5 on 2023-01-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_merch_cat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="merch",
            old_name="cat",
            new_name="cat_id",
        ),
    ]
