# Generated by Django 4.1.5 on 2023-01-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_cat_merch_cat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merch",
            name="cat_id",
        ),
    ]
