# Generated by Django 4.1.5 on 2023-01-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_merch_cat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="merch",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
        ),
    ]
