# Generated by Django 4.1.5 on 2023-01-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_merch_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merch",
            name="category",
            field=models.ForeignKey(
                null=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
        ),
    ]
