# Generated by Django 4.1.5 on 2023-01-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_merch_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merch",
            name="category",
        ),
    ]
